### ISSUE TITLE
debian10 arm64 radxa zero fail to install Mu Editor

### ISSUE THREAD

**Issue by 6SwC** [mu-editor/crash-reports#219] opened 2022-07-07 17:45 UTC
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: C
Platform: Linux 5.10.69-12-amlogic-g98700611d064 #amlogic SMP PREEMPT Tue Jun 14 12:47:53 UTC 2022 aarch64

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mu/app.py", line 159, in run
    raise ex
  File "/usr/local/lib/python3.7/dist-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 772, in create
    self.install_baseline_packages()
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 883, in install_baseline_packages
    wheels.download(zipped_wheels_filepath, logger)
  File "/usr/local/lib/python3.7/dist-packages/mu/wheels/__init__.py", line 178, in download
    zip_wheels(zip_filepath, temp_dirpath, logger)
  File "/usr/local/lib/python3.7/dist-packages/mu/wheels/__init__.py", line 149, in zip_wheels
    with zipfile.ZipFile(zip_filepath, "w") as z:
  File "/usr/lib/python3.7/zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/dist-packages/mu/wheels/1.1.1.zip'

```

log file:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mu/app.py", line 159, in run
    raise ex
  File "/usr/local/lib/python3.7/dist-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 772, in create
    self.install_baseline_packages()
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 883, in install_baseline_packages
    wheels.download(zipped_wheels_filepath, logger)
  File "/usr/local/lib/python3.7/dist-packages/mu/wheels/__init__.py", line 178, in download
    zip_wheels(zip_filepath, temp_dirpath, logger)
  File "/usr/local/lib/python3.7/dist-packages/mu/wheels/__init__.py", line 149, in zip_wheels
    with zipfile.ZipFile(zip_filepath, "w") as z:
  File "/usr/lib/python3.7/zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/dist-packages/mu/wheels/1.1.1.zip'
```

**Comment by carlosperate** [comment] 2022-07-08 08:19
Thanks for the report, I'll closing as a duplicate of #220, and continue the conversation over there 👍

**Closed as not planned by carlosperate** 2022-07-08 08:19 UTC
Labels: need-logs, OS: Linux
