### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by SufjanK** [mu-editor/crash-reports#545] opened 2023-09-23 23:13 UTC
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_US
Platform: Windows 10 10.0.22621 AMD64

```
sufjan\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\interface\main.py", line

```

**Comment by carlosperate** [comment] 2023-10-18 16:01
I'll close this one as a duplicate of https://github.com/mu-editor/crash-reports/issues/544 and we can continue the debugging over there 👍

**Closed as completed by carlosperate** 2023-10-18 16:01 UTC
