### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Narctexed** [mu-editor/crash-reports#258] opened 2022-08-24 11:27 UTC
[mu.log](https://github.com/mu-editor/crash-reports/files/9415628/mu.log)
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: en_US
Platform: Windows 10 10.0.19044 AMD64

```
ironment.py", line 828, in create
    self.install_baseline_packages()
  File "C:\Users\Thofikkur Rokhman\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 935, in install_baseline_packages
    logger.info("pip version: %s", compact(self.pip.version()))
  File "C:\Users\Thofikkur Rokhman\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 339, in version
    return self.run("--version")
  File "C:\Users\Thofikkur Rokhman\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 271, in run
    result = self.process.run_blocking(
  File "C:\Users\Thofikkur Rokhman\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 147, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\Thofikkur Rokhman\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 211, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 101:
Unable to create process using 'C:\Users\Thofikkur Rokhman\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Thofikkur Rokhman\AppData\Local\python\mu\mu_venv-38-20220824-182624\scripts\pip.exe" --version --disable-pip-version-check'

```

**Comment by carlosperate** [comment] 2022-08-24 12:16
Closing as a duplicate of https://github.com/mu-editor/crash-reports/issues/257, let's use that thread to continue this debugging.

**Closed as not planned by carlosperate** 2022-08-24 12:16 UTC
